"""
strategies/base.py — Abstract base class for all trading strategies.

Every strategy must:
- Have a unique `type` string (used in the DB and registry)
- Implement `generate_signals()` returning a list of Signal objects
- Implement `get_default_params()` returning a dict of configurable parameters
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    company: str
    action: str              # "BUY" or "SELL"
    entry_price: float
    sl_price: float
    t1: float
    t2: float
    t3: float
    quantity: int
    strategy_id: str
    account_id: str
    reason: str = ""         # human-readable explanation shown in UI

    @property
    def r_value(self) -> float:
        return self.entry_price - self.sl_price

    @property
    def risk_amount(self) -> float:
        return self.r_value * self.quantity

    @property
    def reward_risk_ratio(self) -> float:
        if self.r_value <= 0:
            return 0.0
        return (self.t3 - self.entry_price) / self.r_value


class BaseStrategy(ABC):
    """Abstract base for all strategies."""

    name: str = "Unnamed Strategy"
    type: str = "UNKNOWN"
    description: str = ""

    @abstractmethod
    def generate_signals(
        self,
        ipo_list: list[dict],
        ohlc_data: dict[str, list[dict]],
        params: dict,
        capital: float,
        risk_pct: float,
        existing_holdings: list[dict],
    ) -> list[Signal]:
        """
        Scan the universe and return actionable signals RIGHT NOW.

        Args:
            ipo_list: List of IPO dicts from Chittorgarh scraper
            ohlc_data: {symbol: [bar_dicts]} OHLC cache
            params: Strategy-specific parameters (overrides defaults)
            capital: Allocated capital for this strategy on this account (₹)
            risk_pct: Fraction of capital to risk per trade (e.g. 0.01 = 1%)
            existing_holdings: Current holdings for this account (to avoid re-entry)

        Returns:
            List of Signal objects
        """
        ...

    @abstractmethod
    def get_default_params(self) -> dict:
        """Return default parameter values shown in the Strategies config page."""
        ...

    def _already_holding(self, symbol: str, existing_holdings: list[dict]) -> bool:
        """Check if the account already holds this symbol."""
        return any(h.get("symbol") == symbol for h in existing_holdings)
